[package]
name = "symlink-builder"
version = "0.1.1"
edition = "2024"

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
toml  = { version = "0.9", default-features = false, features = ["parse", "serde"] }
